name: DailySign

on:  
  schedule:
    - cron:  0 16 * * * 
  issues:
    types: [opened, edited, milestoned]

jobs:
  Glados-Checkin:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
    - name: Debug
      uses: P3TERX/debugger-action@master
                   
    - name: requirements
      run: |
        pip3 install -r requirements.txt

    - name: Checkin

      run: |
        cd DailySign/glados-checkin-master/
        python3 checkin.py 

      env: 

        #SERVE: ${{ secrets.SERVE }}

        SCKEY: ${{ secrets.SCKEY }}

        COOKIE: ${{ secrets.GLADOSCOOKIE }}
    - name: Debug
      uses: P3TERX/debugger-action@master