name: DailySign

on:
  # push:
  #   branches:
  #     - master
  schedule:
    - cron:  0 16 * * * 
  issues:
    types: [opened, edited, milestoned]

jobs:
  # Glados-Checkin: https://github.com/xiaomustudent
  Glados-Checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        run: |
          sudo apt update && \
          sudo apt install python3

      - name: Checkin
        run: |
          cd ./DailySign/glados-checkin-master
          pip3 install -r requirements.txt
          python3 checkin.py 
        env: 
          #SERVE: ${{ secrets.SERVE }}
          SCKEY: ${{ secrets.SCKEY }}
          COOKIE: ${{ secrets.GLADOSCOOKIE }}

      # 调试Debug   
      # - name: SSH connection to Actions
      #   if: ${{ failure() }}
      #   uses: P3TERX/debugger-action@master
  
  JD-Checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Checkout ruicky/jd_sign_bot
      #   uses: actions/checkout@v2
      #   with:
      #     repository: ruicky/jd_sign_bot
      #     path: jd_sign_bot

      - name: Checkout lxk0301/scripts
        uses: actions/checkout@v2
        with:
          repository: lxk0301/scripts
          path: scripts


      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      # - name: Run app.js in jd_sign_bot
      #   run: |
      #     cd ./jd_sign_bot/
      #     npm install
      #     node app.js
      #   env:
      #     JD_COOKIE: ${{ secrets.JD_COOKIE }}
      #     PUSH_KEY: ${{ secrets.SCKEY }}

      - name: Run app.js in scripts
        run: |
          cd ./scripts/
          npm install
          node jd_bean_sign.js
          node jd_blueCoin.js
          node jd_joy.js
          node jd_joy_feedPets.js
          node jd_joy_reward.js
          node jd_joy_steal.js
          node jd_moneyTree.js
          node jd_pet.js
          node jd_speed.js
          node jd_superMarket.js
          node jd_unsubscribe.js
          node jd_fruit.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          PUSH_KEY: ${{ secrets.SCKEY }}
          PetShareCodes: ''
          FruitShareCodes: ''

      # - name: SSH connection to Actions
      #   if: ${{ failure() }}
      #   uses: P3TERX/debugger-action@master

  _52POJIE:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        run: |
          sudo apt update && \
          sudo apt install python3

      - name: Checkin
        run: |
          cd ./DailySign/52pojie
          pip3 install -r requirements.txt
          python3 52pojie.py 
        env: 
          #SERVE: ${{ secrets.SERVE }}
          SCKEY: ${{ secrets.SCKEY }}
          COOKIE: ${{ secrets.POJIECOOKIE }} 

      # - name: SSH connection to Actions
      #   if: ${{ failure() }}
      #   uses: P3TERX/debugger-action@master