name: DailySign

on:
  push:  
  schedule:
    - cron:  0 16 * * * 
  issues:
    types: [opened, edited, milestoned]

jobs:
  Glados-Checkin:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3

    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@master

    - name: Checkin
      run: |
        cd ./DailySign/glados-checkin-master
        pip3 install -r requirements.txt
        python3 checkin.py 

      env: 

        #SERVE: ${{ secrets.SERVE }}

        SCKEY: ${{ secrets.SCKEY }}

        COOKIE: ${{ secrets.GLADOSCOOKIE }}