name: DailySign

on:
  push:  
  schedule:
    - cron:  0 16 * * * 
  issues:
    types: [opened, edited, milestoned]

jobs:
  # Glados-Checkin: https://github.com/xiaomustudent
  Glados-Checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        run: |
          sudo apt update && \
          sudo apt install python3

      - name: Checkin
        run: |
          cd ./DailySign/glados-checkin-master
          pip3 install -r requirements.txt
          python3 checkin.py 
        env: 
          #SERVE: ${{ secrets.SERVE }}
          SCKEY: ${{ secrets.SCKEY }}
          COOKIE: ${{ secrets.GLADOSCOOKIE }}

      # 调试Debug   
      # - name: SSH connection to Actions
      #   if: ${{ failure() }}
      #   uses: P3TERX/debugger-action@master
  
  JD-Checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
        with:
          repository: ruicky/jd_sign_bot 
          
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Run app
        run: npm install
      - run: node app.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          PUSH_KEY: ${{ secrets.SCKEY }}

      # - name: SSH connection to Actions
      #   if: ${{ failure() }}
      #   uses: P3TERX/debugger-action@master

  _52POJIE:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        run: |
          sudo apt update && \
          sudo apt install python3

      - name: Checkin
        run: |
          cd ./DailySign/52pojie
          pip3 install -r requirements.txt
          python3 52pojie.py 
        env: 
          #SERVE: ${{ secrets.SERVE }}
          SCKEY: ${{ secrets.SCKEY }}
          COOKIE: ${{ secrets.POJIECOOKIE }} 

      - name: SSH connection to Actions
        if: ${{ failure() }}
        uses: P3TERX/debugger-action@master