# This is a basic workflow to help you get started with Actions

name: EpicGames

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  release:
    types: [published]
#   issues:
#     types: [opened, edited, milestoned]
#   schedule:
#     - cron: "25 2 * * *"
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  MainWork:
    runs-on: ubuntu-latest
#     steps:      
#       - name: Clone Workflow Repository
#         uses: actions/checkout@v2

#       - name: Clone Claimer Repository
#         uses: actions/checkout@v2
#         with:
#           repository: Revadike/epicgames-freebies-claimer
#           path: workdir



#       # 在 'Settings' - 'Secrets' 添加 EMAIL (你的 Epic 邮箱)，PASSWD (你的 Epic 密码)，SECRET（二步验证 Secret）
#       - name: Get Gifts
#         run: |
#           cd workdir
#           npm install
#           node start '${{ secrets.EpicGames_Email_1 }}' '${{ secrets.EpicGames_Password_1 }}' 0 '${{ secrets.EpicGames_2FA }}' > games.info
      
#       - name: Edit Games.info
#         if: always()
#         run: |
#           cd workdir
#           sed -i '1d' games.info
#           sed -i 's/Successfully claimed/成功领取/' games.info
#           sed -i 's/was already claimed for this account/已经领取/' games.info
#           sed -i '$d' games.info
#           date --rfc-3339=seconds >> ../games.info
#           cat games.info >> ../games.info
#           echo >> ../games.info

# #       如果需要推送到 Telegram 用来提示，取消注释以下内容
# #       这部分的内容可以查看 https://www.github.com/appleboy/telegram-action
#       - name: Send Gift Info
#         if: always()
#         uses: appleboy/telegram-action@master
#         with:
#           to: ${{ secrets.TELEGRAM_CHATID }}
#           token: ${{ secrets.TELEGRAM_TOKEN }}
#           format: markdown
#           message_file: workdir/games.info



    steps:
        - name: Setup repo
          uses: actions/checkout@v2
          with:
              repository: "Revadike/epicgames-freebies-claimer"

        - name: Setup Node.js
          uses: actions/setup-node@v1

        - name: Install dependencies
          run: yarn

        - name: Fix Epicgames Client Bug
          run: mkdir -p .egstore
          
        - name: SSH connection to Actions
          uses: P3TERX/debugger-action@master

        - name: Get Epic Freebies
          id: epic
          run: yarn start '${{ secrets.EpicGames_Email_1 }}' '${{ secrets.EpicGames_Password_1 }}' 1 '${{ secrets.EpicGames_2FA }}'

