name: freenom

on:
  schedule:
    - cron: '0 1 * * *'
  issues:
    types: [opened, edited, milestoned]

jobs:
  run_php:

    runs-on: ubuntu-latest
    
    steps:
    - name: setup-php
      uses: khs1994-docker/actions-setup-php@0.0.1

    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
          repository: luolongfei/freenom 
          path: freenom

    - name: Edit Config.php & .env
      run: |
       mv -f freenomconfig/.[!.]* ./freenom/
       
       cd freenom
       for line in config.php
       do
         echo $line
       done
       ls -a && php run > log.log 2>&1
 
    - name: Send Gift Info
      if: always()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHATID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message_file: freenom/log.log
